### ISSUE TITLE
hi ,where to find "ImportError: cannot import name 'hparam_pb2' from 'model_search.proto' (unknown location)"

### ISSUE THREAD

**Issue by mathpopo** [google/model_search#17]
![1111](https://user-images.githubusercontent.com/21274466/108943104-2cdec880-7693-11eb-893a-161f45ab11a4.jpeg)

**Comment by Mrmdzz** [comment]
[https://github.com/google/model_search/issues/3](url)

**Comment by chsher** [comment]
Having the same issue.

**Comment by mmuratarat** [comment]
Did you compile all the proto files by using the protoc compiler?

**Comment by yqt126** [comment]
same issue

**Comment by Gvanderl** [comment]
> Did you compile all the proto files by using the protoc compiler?

How would one do that ? This project could really use some installation instructions...
