### ISSUE TITLE
What does "experiment_owner" mean? I don’t understand how to fill in this parameter???

### ISSUE THREAD

**Issue by Mrmdzz** [google/model_search#18]
error:UnparsedFlagAccessError: Trying to access flag --mlmd_default_sqllite_filename before flags were parsed.

**Comment by hadehuang** [comment]
The same problem.

**Comment by hadehuang** [comment]
May we need install a sqllite first.

**Comment by hadehuang** [comment]
This the bug, and fixed now 

#8

**Comment by beboplove** [comment]
Im the owner dont change my github

**Comment by beboplove** [comment]
I eric robert davis 11011986 own all

**Comment by hanna-maz** [comment]
experiment_owner is a string identifier of a user. You can put any random string. It helps when multiple users are running model search.

The flag comment is fixed in the new version from today.
