### ISSUE TITLE
NewRandomAccessFile failed to Create/Open

### ISSUE THREAD

**Issue by Shoot-to-root** [google/model_search#19]
`NotFoundError: NewRandomAccessFile failed to Create/Open: model_search/model_search/configs/dnn_config.pbtxt : The system cannot find the path specified.
; No such process`

It seems like the path "model_search" was imported twice...Any idea how to solve it? Thanks in advance!

**Comment by srivatsan88** [comment]
@Shoot-to-root .. Can you paste the code where you are getting error. If it is in trainer object you can give direct path as below

trainer = single_trainer.SingleTrainer(
    data=csv_data.Provider(label_index=0, logits_dimension=2, record_defaults=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], filename="default.csv"),
    spec='model_search/configs/dnn_config.pbtxt')

You can check my working notebook here - https://github.com/srivatsan88/YouTubeLI/blob/master/Model_Architecture_Search.ipynb

**Comment by Shoot-to-root** [comment]
> 
> 
> @Shoot-to-root .. Can you paste the code where you are getting error. If it is in trainer object you can give direct path as below
> 
> trainer = single_trainer.SingleTrainer(
> data=csv_data.Provider(label_index=0, logits_dimension=2, record_defaults=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0], filename="default.csv"),
> spec='model_search/configs/dnn_config.pbtxt')
> 
> You can check my working notebook here - https://github.com/srivatsan88/YouTubeLI/blob/master/Model_Architecture_Search.ipynb

It works! Thank you, you're a lifesaver!
