### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by VictorT787** [google/model_search#2]
Hello, 
It setup.py missing, or I'm missing something?

Thanks, 
Vic

**Comment by mzeidhassan** [comment]
I have the same question. Can this be installed?

**Comment by manugarri** [comment]
just clone the repo and cd into the folder.

I have to say this repo structure is pretty bad for an OSS project.

**Comment by tagma** [comment]
For Colab:

!git clone -l -s https://github.com/google/model_search.git
%cd model_search
!pip install -r requirements.txt
!protoc --python_out=./ model_search/proto/phoenix_spec.proto
!protoc --python_out=./ model_search/proto/hparam.proto
!protoc --python_out=./ model_search/proto/distillation_spec.proto
!protoc --python_out=./ model_search/proto/ensembling_spec.proto
!protoc --python_out=./ model_search/proto/transfer_learning_spec.proto

import model_search
from model_search import constants
from model_search import single_trainer
from model_search.data import csv_data

**Comment by VictorT787** [comment]
Thank you, everyone. My apologies, as I saw the official release I did not see the setup.py. I thought that there was something missing.
