### ISSUE TITLE
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --mlmd_default_sqllite_filename before flags were parsed

### ISSUE THREAD

**Issue by lsiem** [google/model_search#25]
I get the error when I run the code snippet from the project page:

`Traceback (most recent call last):
  File "btc.py", line 14, in <module>
    trainer.try_models(
  File "/home/lasse/Development/projects/btcpred/model_search/model_search/single_trainer.py", line 56, in try_models
    phoenix_instance = phoenix.Phoenix(
  File "/home/lasse/Development/projects/btcpred/model_search/model_search/phoenix.py", line 239, in __init__
    self._metadata = ml_metadata_db.MLMetaData(phoenix_spec, study_name,
  File "/home/lasse/Development/projects/btcpred/model_search/model_search/metadata/ml_metadata_db.py", line 84, in __init__
    if FLAGS.mlmd_default_sqllite_filename:
  File "/home/lasse/Development/projects/btcpred/.env/lib/python3.8/site-packages/absl/flags/_flagvalues.py", line 498, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --mlmd_default_sqllite_filename before flags were parsed.
`

**Comment by hadehuang** [comment]
Please refer this issue #8

**Comment by KevinRyu** [comment]
Hello,

I also have similar problem. I read issue #8 but I don't understand what should I do. 

In my case, 
if self.__dict__['__flags_parsed'] or fl[name].present:
--> Condition shows False & 0 in order.

FLAGS = flags.FLAGS in /model_search/metadata/ml_metadata_db.py
 Is this code line for parsing? What can I do before this line?

Would someone give me some hints?

**Comment by KevinRyu** [comment]
> Hello,
> 
> I also have similar problem. I read issue #8 but I don't understand what should I do.
> 
> In my case,
> if self.**dict**['__flags_parsed'] or fl[name].present: (in _flagvalues.py)
> --> Condition shows False & 0 in order.
> 
> FLAGS = flags.FLAGS in /model_search/metadata/ml_metadata_db.py
> Is this code line for parsing? What can I do before this line?
> 
> Would someone give me some hints?

I solved this error by adding import sys and argv = FLAGS(sys.argv) in ml_metadata_db.py

**Comment by lsiem** [comment]
> Hello,
> 
> I also have similar problem. I read issue #8 but I don't understand what should I do.
> 
> In my case,
> if self.**dict**['__flags_parsed'] or fl[name].present: (in _flagvalues.py)
> --> Condition shows False & 0 in order.
> 
> FLAGS = flags.FLAGS in /model_search/metadata/ml_metadata_db.py
> Is this code line for parsing? What can I do before this line?
> 
> Would someone give me some hints?

I was able to fix the problem by taking the commit from https://github.com/google/model_search/pull/8#issue-577118576

**Comment by davidxiaozhi** [comment]
from absl import app
from absl import flags
from absl import logging

FLAGS = flags.FLAGS 

you must import it in your python script ,use app.run(main)

**Comment by hanna-maz** [comment]
This should be fixed in the new version from today.
