### ISSUE TITLE
model_search not available yet on pip

### ISSUE THREAD

**Issue by GermanCM** [google/model_search#7]
When is it going to be available as a pip package? 

![image](https://user-images.githubusercontent.com/32896503/108625114-573d4580-7449-11eb-8bc9-dc28cd6ebdeb.png)

Thanks a million!

**Comment by jasonk33** [comment]
is there another way to install it besides pip? @hanna-maz

**Comment by srivatsan88** [comment]
@jasonk33 .. I have highlighted install steps in this video if it helps. Install was not straight forward but not that complex as well - https://www.youtube.com/watch?v=-7TZ-IKMJi8

**Comment by chenxingqiang** [comment]
this repo use bazel building the  project.

**Comment by GermanCM** [comment]
video about cloning and installing dependencies indicated by @srivatsan88
